// <auto-generated />
namespace Lab01_151524026_Renaldy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class onetomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onetomany));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261543176_one-to-many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
